### ISSUE TITLE
ipv6 and addresses published under mDNS

### ISSUE THREAD

**Issue by NorthernMan54** [homebridge/bonjour#14]
### Analysis

I was investigating some issues with ipv6 support with my plugins and noticed this behaviour when looking into connectivity issues.   When running under MacOS, and using the bonjour-hap advertiser I saw multiple ipv6 address advertised for my homebridge instance.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/19808920/208303662-f901d07e-0559-4822-9fd4-20a7ad2139cd.png">

Looking at ifconfig on my Mac, I see the multiple ipv6 interfaces and ipv6 address, but majority are marked inactive with the primary interface being `fe80::cf2:38da:84b:10b3%en0`

Here is the same when using the ciao advertiser

<img width="338" alt="image" src="https://user-images.githubusercontent.com/19808920/208303999-53abfd72-aa11-4818-bb4d-a444ae7ca6b0.png">

@Supereg Are you seeing something similar in your environments ?  I'm wondering if these inactive ipv6 address under bonjour-hap could be potential issues with the recent updates ?  Should be recommending not to use bonjour-hap under ipv6 environments ?

### Expected Behavior

not sure

### Steps To Reproduce

Use the advertiser `bonjour-hap`

### Logs

```markdown
none
```

### Configuration

```json
none
```

### Environment

- OS: MacOS 12.6.2
- Software: Homebridge homebridge v1.6.0-beta.4
- Node: node v18.12.0
- npm:

### Process Supervisor

hb-service

**Comment by ebaauw** [comment]
I have a native dual-stack Internet connection, with a global IPv6 address range provided by my ISP.

On my Mac, running Ventura 13.1, using `ciao` as advertiser, Homebridge advertises the IPv4, local-link IPv6, and global IPv6 addresses on `en0` (Ethernet) and `en1` (WiFi).  It also includes the loopback addresses from `lo0`, as in your case.  This doesn't seem right to me.

Om my Raspberry Pi, running Raspbian bullseye, using `avahi` as advertiser, Homebridge advertises the IPv4 and public IPv6 addressss, but not the local-link IPv6 address.  This doesn't seem right to me either.  Might this be the cause of the 10-30s delays I'm seeing since the architecture upgrade when HomeKit updates the accessory state?  I don't see these on my Dev/Test home (using a different iCloud account), only using Homebridge on macOS, nor on my secondary home (using the same iCloud account, but since the architecture upgrade without a home hub, as they now only support a single home, rather than all homes in the iCloud account - gotta love these undocumented "features" by Apple).

My Eve light strip and Eve energy strip advertise their IPv4 and IPv6 local-link addresses.  I don't know if they even acquired a global IPv6 address.  My Sony TV advertises the IPv4, local-link IPv6 and global IPv6 addresses.

My Eve devices with Thread advertise the `fd82:...` IPv6 address on the Thread network (on `_hap._udp.`).

**Comment by ebaauw** [comment]
Updates:
- The loopback addresses only show on the Mac itself; when running _Discovery_ on my iPhone, they're not included.
- After changing the advertiser to `ciao`, Homebridge on my Raspberry Pi now advertises the IPv4, local-link IPv6, and global IPv6 addresses.   Unfortunately, my delays are still present.  They definitely are happening in the home hub (Apple TV): when starting Home at the same time on my iPhone and iPad, both show _Updating_ on all accessories (incl. those with native HomeKit support), and show the actual state at the same time.
